add AnalyticsTable
LetSquad/kalita pull request #166
Opened 2023-02-09 23:25 UTC by progruzovik

2023-02-10 16:54 UTC, IvanSavoskin requested changes

2023-02-10 16:54 UTC, IvanSavoskin commented on src/components/Analytics/AnalyticsTable/AnalyticsTable.tsx
> +                isChartMode
Давай разнесем это на два отдельных компонента. Не очень хорошо, что две разные сущности в одном компоненте лежат. И код станет проще и понятнее

2023-02-10 16:54 UTC, IvanSavoskin commented on src/components/BrokeragePortfolioTable/Table.tsx
> +            labels: currentPortfolio.positions.map((row) => (row.name ? row.name : row.ticker)),
row.name ?? row.ticker

2023-02-10 19:01 UTC, progruzovik commented on src/components/Analytics/AnalyticsTable/AnalyticsTable.tsx
> +                isChartMode
Разделил на AnalyticsTable и AnalyticsChart

2023-02-10 19:01 UTC, progruzovik commented on src/components/BrokeragePortfolioTable/Table.tsx
> +            labels: currentPortfolio.positions.map((row) => (row.name ? row.name : row.ticker)),
Поправил

2023-02-11 10:20 UTC, IvanSavoskin approved these changes

2023-02-11 10:22 UTC, merged